name: FRED
description: A wrapper on the FRED API
node_identifier: fred
platforms:
  - AWS Lambda
  - Docker
  - GCP Functions
data_sources:
  - name: FRED
    url: https://fred.stlouisfed.org/
parameters:
  - dataset
  - rows
